# Generated by Django 2.2.16 on 2023-02-13 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название скидки')),
                ('value', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Скидка не может быть меньше 1%'), django.core.validators.MaxValueValidator(100, message='Скидка не может быть больше 100%')])),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(50, message='Минимальное значение: 50')], verbose_name='Цена')),
                ('discount', models.ManyToManyField(blank=True, to='simple_strape.Discount', verbose_name='Скидки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название налога')),
                ('value', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Налог не может быть меньше 1%'), django.core.validators.MaxValueValidator(100, message='Налог не может быть больше 99%')])),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название корзины')),
                ('items', models.ManyToManyField(to='simple_strape.Item')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, to='simple_strape.Tax', verbose_name='Налои'),
        ),
    ]
