# Generated by Django 2.2.16 on 2023-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_strape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.ManyToManyField(blank=True, to='simple_strape.Tax', verbose_name='Налоги'),
        ),
    ]
