# Generated by Django 2.2.16 on 2023-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_strape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='defoult_name', max_length=200, verbose_name='Название транзакции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='simple_strape.Item', verbose_name='Товар'),
        ),
    ]
